### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by Jorzef** [Tron0xHex/uplay-r1-loader#1]
First time compiling with rust used command rustc build.rs and i got these errors:

![image](https://user-images.githubusercontent.com/1571301/117555642-cdb90f00-b058-11eb-9650-c821a73ab029.png)

**Comment by Re0xCat** [comment]
@Jorzef Use commands from build_inst.txt file.

**Comment by Jorzef** [comment]
Solved thank you!
